# Generated by Django 4.2.27 on 2025-12-15 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('current_orders_count', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('location_description', models.CharField(blank=True, max_length=200)),
                ('courier', models.OneToOneField(limit_choices_to={'role': 'COURIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='courier_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Courier Statuses',
            },
        ),
    ]
