# Generated by Django 4.2.27 on 2025-12-14 15:12

from django.db import migrations
from decimal import Decimal


def create_default_pricing(apps, schema_editor):
    """Create default pricing configuration"""
    PricingConfig = apps.get_model('orders', 'PricingConfig')
    User = apps.get_model('accounts', 'User')
    
    # Get or create an admin user for the pricing config
    admin_user = User.objects.filter(role='ADMIN').first()
    if not admin_user:
        # Create a system admin user if none exists
        admin_user = User.objects.create_user(
            username='system_admin',
            email='admin@deliveryplatform.com',
            password='temp_password_123',
            role='ADMIN',
            first_name='System',
            last_name='Admin'
        )
    
    # Create default pricing configuration if none exists
    if not PricingConfig.objects.exists():
        PricingConfig.objects.create(
            base_fee=Decimal('50.00'),
            per_km_rate=Decimal('20.00'),
            is_active=True,
            created_by=admin_user
        )


def reverse_default_pricing(apps, schema_editor):
    """Remove default pricing configuration"""
    PricingConfig = apps.get_model('orders', 'PricingConfig')
    User = apps.get_model('accounts', 'User')
    
    # Remove default pricing config
    PricingConfig.objects.filter(
        base_fee=Decimal('50.00'),
        per_km_rate=Decimal('20.00')
    ).delete()
    
    # Remove system admin user if it was created
    User.objects.filter(username='system_admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('accounts', '0001_initial'),  # Ensure accounts app is migrated first
    ]

    operations = [
        migrations.RunPython(create_default_pricing, reverse_default_pricing),
    ]
