# Generated by Django 4.2.27 on 2025-12-14 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("DAILY_ORDERS", "Daily Orders"),
                            ("DAILY_REVENUE", "Daily Revenue"),
                            ("COURIER_PERFORMANCE", "Courier Performance"),
                            ("CUSTOMER_ACTIVITY", "Customer Activity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metric_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("date", models.DateField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("metric_type", "date", "related_user")},
            },
        ),
    ]
