#!/bin/bash
# TypeScript Cache Cleanup Script
# Automatically generated by performance optimizer

CACHE_DIR=".typescript-cache"
MAX_AGE_DAYS=30

echo "🧹 Cleaning up TypeScript cache..."

# Remove old cache files
find "$CACHE_DIR" -name "*.tsbuildinfo" -mtime +$MAX_AGE_DAYS -delete
find "$CACHE_DIR" -name "*.cache" -mtime +$MAX_AGE_DAYS -delete

# Compress old performance metrics
find "$CACHE_DIR" -name "performance-metrics-*.json" -mtime +$MAX_AGE_DAYS -exec gzip {} \;

echo "✅ Cache cleanup completed"
